services:
  easywire:
    image: 
      killyp/easywire:latest
    container_name: 
      easywire
    ports:
      - "80:8080"
      - "51820:51820/udp"
    environment:
      - HOST=
      - PASSWORD=
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - wireguard_config:/etc/wireguard
      - easywire_config:/app/keys
    # restart: unless-stopped
    
volumes: 
  wireguard_config:
  easywire_config: