services:
  easywire:
    build:
      context: .
      dockerfile: EasyWire/Dockerfile
    ports:
      - "5000:8080"
      - "51820:51820/udp"
    environment:
      - HOST=
      - PASSWORD=
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - wireguard_config:/etc/wireguard
      - easywire_keys:/app/keys
    # restart: unless-stopped
    
volumes:
  wireguard_config:
  easywire_keys: