services:
  easywire:
    build:
      context: .
      dockerfile: EasyWire/Dockerfile
    ports:
      - "5000:8080"
      - "51820:51820/udp"
    environment:
      - WG_HOST=REPLACE_ME
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - wireguard:/etc/wireguard
    restart: unless-stopped
    
volumes: 
  wireguard: